// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: proto/anagram.proto

package anagrampb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnagramRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *AnagramRequest) Reset() {
	*x = AnagramRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_anagram_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnagramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnagramRequest) ProtoMessage() {}

func (x *AnagramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anagram_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnagramRequest.ProtoReflect.Descriptor instead.
func (*AnagramRequest) Descriptor() ([]byte, []int) {
	return file_proto_anagram_proto_rawDescGZIP(), []int{0}
}

func (x *AnagramRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AnagramRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type AnagramResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsAnagram bool `protobuf:"varint,1,opt,name=isAnagram,proto3" json:"isAnagram,omitempty"`
}

func (x *AnagramResponse) Reset() {
	*x = AnagramResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_anagram_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnagramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnagramResponse) ProtoMessage() {}

func (x *AnagramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anagram_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnagramResponse.ProtoReflect.Descriptor instead.
func (*AnagramResponse) Descriptor() ([]byte, []int) {
	return file_proto_anagram_proto_rawDescGZIP(), []int{1}
}

func (x *AnagramResponse) GetIsAnagram() bool {
	if x != nil {
		return x.IsAnagram
	}
	return false
}

var File_proto_anagram_proto protoreflect.FileDescriptor

var file_proto_anagram_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x6e, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x22, 0x40,
	0x0a, 0x0e, 0x41, 0x6e, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x22, 0x2f, 0x0a, 0x0f, 0x41, 0x6e, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x41, 0x6e, 0x61, 0x67, 0x72, 0x61, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x41, 0x6e, 0x61, 0x67, 0x72, 0x61,
	0x6d, 0x32, 0x47, 0x0a, 0x07, 0x41, 0x6e, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x3c, 0x0a, 0x05,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x17, 0x2e, 0x61, 0x6e, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x2e,
	0x41, 0x6e, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x61, 0x6e, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x41, 0x6e, 0x61, 0x67, 0x72, 0x61, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x75, 0x6e, 0x61, 0x72, 0x79, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x6c, 0x79, 0x2f, 0x75, 0x6e, 0x61, 0x72, 0x79, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x3b, 0x61, 0x6e, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_anagram_proto_rawDescOnce sync.Once
	file_proto_anagram_proto_rawDescData = file_proto_anagram_proto_rawDesc
)

func file_proto_anagram_proto_rawDescGZIP() []byte {
	file_proto_anagram_proto_rawDescOnce.Do(func() {
		file_proto_anagram_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_anagram_proto_rawDescData)
	})
	return file_proto_anagram_proto_rawDescData
}

var file_proto_anagram_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_anagram_proto_goTypes = []interface{}{
	(*AnagramRequest)(nil),  // 0: anagram.AnagramRequest
	(*AnagramResponse)(nil), // 1: anagram.AnagramResponse
}
var file_proto_anagram_proto_depIdxs = []int32{
	0, // 0: anagram.Anagram.Check:input_type -> anagram.AnagramRequest
	1, // 1: anagram.Anagram.Check:output_type -> anagram.AnagramResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_anagram_proto_init() }
func file_proto_anagram_proto_init() {
	if File_proto_anagram_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_anagram_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnagramRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_anagram_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnagramResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_anagram_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_anagram_proto_goTypes,
		DependencyIndexes: file_proto_anagram_proto_depIdxs,
		MessageInfos:      file_proto_anagram_proto_msgTypes,
	}.Build()
	File_proto_anagram_proto = out.File
	file_proto_anagram_proto_rawDesc = nil
	file_proto_anagram_proto_goTypes = nil
	file_proto_anagram_proto_depIdxs = nil
}
